import type { Metadata } from "next";
import { inter } from "./utils/font";
import "./globals.css";
import classNames from "classnames";

export const metadata: Metadata = {
  title: "Shop.co",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={classNames(inter.className)}>
      <body>{children}</body>
    </html>
  );
}
